[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts"]
ffi = true # caution allow foundry to run commands directly on your machine (recommeded to keep off)  

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
